### ISSUE TITLE
Questions about model.py

### ISSUE THREAD

**Issue by wgmao** [ofirnachum/sequence_gan#3]
In model.py, the embedding matrix `g_embeddings` is appended to the generator parameter set `g_params`. Then `g_embeddings` is updated when executing `self.g_grad = tf.gradients(self.g_loss, self.g_params)` and following operations.

I just wonder if we need to update the embedding matrix as we update the generator parameters. As I understand, the embedding matrix only helps to represent the vocabulary as independent vectors. Could we just use a fixed embedding matrix? Thanks.

**Comment by ofirnachum** [comment]
A trainable embedding matrix is often used in scenarios like this.  You could use a fixed embedding matrix, but your resulting model would likely perform worse.
