### ISSUE TITLE
AttributeError: 'module' object has no attribute 'While'

### ISSUE THREAD

**Issue by SeekPoint** [ofirnachum/sequence_gan#4]
rzai@rzai00:~/prj/sequence_gan$ python simple_demo.py 
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "simple_demo.py", line 108, in <module>
    main()
  File "simple_demo.py", line 90, in main
    trainable_model = get_trainable_model()
  File "simple_demo.py", line 41, in get_trainable_model
    learning_rate=LEARNING_RATE)
  File "/home/rzai/prj/sequence_gan/model.py", line 82, in __init__
    _, _, _, self.gen_o, self.gen_x = control_flow_ops.While(
AttributeError: 'module' object has no attribute 'While'
rzai@rzai00:~/prj/sequence_gan$ vim model.py
rzai@rzai00:~/prj/sequence_gan$

**Comment by ofirnachum** [comment]
You're probably using a later version of Tensorflow than what I used when I wrote the code.  I think the new standard way to do these loops is to use tf.while_loop

**Comment by Nopey** [comment]
Pull request #9 switches from while to while_loop, solving this problem.

**Comment by SeekPoint** [comment]
@Nopey 
fixed ,thanks
