### ISSUE TITLE
gpu is slower than cpu for your codes

### ISSUE THREAD

**Issue by npark** [ofirnachum/sequence_gan#8]
Hi,
Thanks for all your response. When I tested your codes, gpu was almost 8 times slower than cpu. Can you guess why?

Thanks.

**Comment by ofirnachum** [comment]
Most of the parameter sizes are set to relatively small values.  Moreover there is no notion of a batch (examples are trained one at a time).  Thus, most of the matrix multiplications are small and so there's little benefit from using GPU.
